apiVersion: v1
kind: Service
metadata:
  name: my-app-service
  namespace: my-app   # Ensure it's in the same namespace as the deployment
spec:
  selector:
    app: my-app
  ports:
    - protocol: TCP
      port: 80        # External port
      targetPort: 8080  # Port your app listens to inside the container
  type: NodePort      # Use LoadBalancer if you're on a cloud provider like AWS/GCP
